--- #YAML:1.0
name:               Dancer-Plugin-Log-DB
version:            0.03
abstract:           log arbitrary messages into a database from within your Dancer application.
author:
    - Nikolay Aviltsev <navi@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Dancer:               1.0
    Dancer::Plugin::Database:  0
    DBD::SQLite:          0
    Test::More:           0
    Time::Piece:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
